name: "Publish to PyPi"

on:
  #  push:
  #    branches:
  #      [ main ]
  #    tags:
  #      - '**'
  #  pull_request:
  #    branches:
  #      [ main ]
  #    tags:
  #      - '**'
  workflow_dispatch:

jobs:
  python-setup:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
      - name: "Install Python"
        run: uv python install
      #        with:
      #          enable-cache: true
      #          cache-dependency-glob: "uv.lock"
      #      - name: "Convert Readme to Markdown"
      #        run: uvx --from Pydowndoc-bin -- downdoc README.adoc
      - name: "Build Package"
        run: uv build
      - name: "Publish Package to PyPi"
        run: uv publish
