name: "Publish"

on: push

jobs:
  python-setup:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
      #        with:
      #          enable-cache: true
      #          cache-dependency-glob: "uv.lock"
      - name: "Build"
        run: uv build
      - name: "Publish"
        run: uv publish