name: "Publish to TestPyPi"

on:
  workflow_dispatch:

#  push:
#    branches:
#      [ main ]
#    tags:
#      - '**'
#    paths-ignore:
#      - 'data/**'
#  pull_request:
#    branches:
#      [ main ]
#    tags:
#      - '**'
#    paths-ignore:
#      - 'data/**'

jobs:
  python-setup:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.13
        run: uv python install 3.13
      #        with:
      #          enable-cache: true
      #          cache-dependency-glob: "uv.lock"
      #      - name: "Convert Readme to Markdown"
      #        run: uvx --from Pydowndoc-bin -- downdoc README.adoc
      - name: "Build"
        run: uv build
      - name: "Publish"
        run: uv publish --index testpypi
